#!/usr/bin/env bash

# script used to generate the package to be given to the student
# It generates tp4ogl-vX-Y-Z-commit.zip containing all the cpp and the
# makefile needed to compile
# It uses the python script studentify.py to generate the cpp file
# with the code for the student to complete.

VERSION=$(git describe --tags | sed -e 's/^v//')
ARCHIVE_NAME=tp1ogl-v${VERSION}

TMPDIR=/tmp

DESTNAME=${TMPDIR}/${ARCHIVE_NAME}
mkdir ${DESTNAME}

cp README.md CMakeLists.txt  helloteapot.cpp  moreteapots.cpp .clang-format  README.md LICENSE ${DESTNAME}
# remove this very script
rm ${DESTNAME}/$0

set -e
cp -r freeglut ${DESTNAME}

echo "Generating archive..."
cd ${TMPDIR}
zip -r ${ARCHIVE_NAME}.zip ${ARCHIVE_NAME}
cd -
mv  ${TMPDIR}/${ARCHIVE_NAME}.zip .

echo "Cleaning up..."
rm -rf ${DESTNAME}